name: 'random package'
on: [push, pull_request]

jobs:
  ubuntu-job:
    name: 'ubuntu job'
    runs-on: ubuntu-latest
    steps:
      - name: 'fetching local'
        uses: 'rchougule/local-action@master'
        with:
          local-testing: 'start'
          local-logging-level: 'some level'
          local-identifier: 'some identifier'
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          local-args: 'some args one two three'
      - name: 'checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'install selenium webdriver'
        run: 'npm install selenium-webdriver'
      - name: 'run test'
        run: 'node index.js'
  macos-job:
    name: 'macos job'
    runs-on: macos-latest
    steps:
      - name: 'fetching local'
        uses: 'rchougule/local-action@master'
        with:
          local-testing: 'start'
          local-logging-level: 'some level'
          local-identifier: 'some identifier'
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          local-args: 'some args one two three'
      - name: 'checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'install selenium webdriver'
        run: 'npm install selenium-webdriver'
      - name: 'run test'
        run: 'node index.js'
  windows-job:
    name: 'windows job'
    runs-on: windows-latest
    steps:
      - name: 'fetching local'
        uses: 'rchougule/local-action@master'
        with:
          local-testing: 'start'
          local-logging-level: 'some level'
          local-identifier: 'some identifier'
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          local-args: 'some args one two three'
      - name: 'checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'install selenium webdriver'
        run: 'npm install selenium-webdriver'
      - name: 'run test'
        run: 'node index.js'