name: 'random package'
on: [pull_request]

jobs:
  ubuntu-job:
    name: 'ubuntu job'
    runs-on: ubuntu-latest
    steps:
      - name: 'fetching local'
        uses: 'rchougule/local-action@master'
        with:
          local-testing: 'start'
          local-logging-level: setup-logs
          local-identifier: 'some identifier'
          build-name: 'this is my ubuntu-META#'
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          local-args: '--proxy-host hostname --proxy-port portname --only-automate --daemon start --key jinga --local-identifier this-is-mine'
      - name: 'checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'install selenium webdriver'
        run: 'npm install selenium-webdriver'
      - name: 'run test'
        run: 'node index.js'
  macos-job:
    name: 'macos job'
    runs-on: macos-latest
    steps:
      - name: 'fetching local'
        uses: 'rchougule/local-action@master'
        with:
          local-testing: 'stop'
          local-logging-level: network-logs
          local-identifier: 'random'
          build-name: 'this is mac os-META#'
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          local-args: '--proxy-host hostname --proxy-port portname --only-automate --daemon start --key jinga --local-identifier this-is-mine'
      - name: 'checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'install selenium webdriver'
        run: 'npm install selenium-webdriver'
      - name: 'run test'
        run: 'node index.js'
  windows-job:
    name: 'windows job'
    runs-on: windows-latest
    steps:
      - name: 'fetching local'
        uses: 'rchougule/local-action@master'
        with:
          local-testing: 'false'
          local-logging-level: 'false random level'
          local-identifier: random doesnt matter i think
          build-name: 'META#-this is windows'
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          local-args: '--proxy-host hostname --proxy-port portname --only-automate --daemon start --key jinga --local-identifier this-is-mine'
      - name: 'checkout the repository'
        uses: 'actions/checkout@v2'
      - name: 'install selenium webdriver'
        run: 'npm install selenium-webdriver'
      - name: 'run test'
        run: 'node index.js'