name: 'random package'
on: [push]

jobs:
  build:
    name: 'some job name'
    runs-on: ubuntu-latest
    steps:
      - name: 'first step of req deb'
        uses: 'rchougule/action-setup@v1'
        with:
          port: 9998